### ISSUE TITLE
Instead a proper error message , we display server error on create leave that overlaps another one

### ISSUE THREAD

**Issue by alinaMBH** [web-innovate/leave-tracking#37]
400 | Bad Request | {"message":"There is a leave-request already created that overlaps with your dates","start":"2017-10-25T21:00:00.000Z","end":"2017-10-27T20:59:59.999Z","status":"pending"}

**Comment by BogdanLivadariu** [comment]
this is as designed for now, these sort of issues will get fixed along with https://github.com/web-innovate/leave-tracking/issues/36
